export const ORG_NAME = "CNAC MURIMA W'ISANGI";

export type FieldType = "text" | "number" | "date" | "textarea" | "select" | "ref";

export type Field = {
  name: string;
  label: string;
  type: FieldType;
  list?: boolean;
  required?: boolean;
  options?: string[];
  refModule?: string;
  suffix?: string;
};

export type ModuleDef = {
  slug: string;
  table: string;
  title: string;
  singular: string;
  description: string;
  group: string;
  labelField: string;
  labelField2?: string;
  fields: Field[];
};

const STATUT = (options: string[]): Field => ({
  name: "statut",
  label: "Statut",
  type: "select",
  list: true,
  options,
});

export const MODULES: ModuleDef[] = [
  {
    slug: "employes",
    table: "employes",
    title: "Employés",
    singular: "Employé",
    description: "Dossiers du personnel : identité, affectation et rémunération de base.",
    group: "Administration / RH",
    labelField: "nom",
    labelField2: "prenom",
    fields: [
      { name: "matricule", label: "Matricule", type: "text", list: true },
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "prenom", label: "Prénom", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "email", label: "E-mail", type: "text" },
      { name: "fonction", label: "Fonction", type: "text", list: true },
      { name: "service", label: "Service", type: "text", list: true },
      { name: "localite", label: "Localité", type: "text" },
      { name: "cni", label: "CNI", type: "text" },
      { name: "date_entree", label: "Date d'entrée", type: "date" },
      { name: "date_sortie", label: "Date de sortie", type: "date" },
      { name: "salaire_base", label: "Salaire de base", type: "number", list: true },
      STATUT(["Actif", "Suspendu", "Retraité", "Parti"]),
    ],
  },
  {
    slug: "conges",
    table: "conges",
    title: "Congés",
    singular: "Congé",
    description: "Demandes et validations de congés du personnel.",
    group: "Administration / RH",
    labelField: "type_conge",
    fields: [
      { name: "employe_id", label: "Employé", type: "ref", refModule: "employes", list: true },
      {
        name: "type_conge",
        label: "Type de congé",
        type: "select",
        list: true,
        required: true,
        options: ["Annuel", "Maladie", "Maternité", "Circonstanciel", "Sans solde"],
      },
      { name: "date_debut", label: "Début", type: "date", list: true },
      { name: "date_fin", label: "Fin", type: "date", list: true },
      { name: "nombre_jours", label: "Nombre de jours", type: "number", list: true },
      { name: "motif", label: "Motif", type: "textarea" },
      STATUT(["En attente", "Approuvé", "Refusé"]),
    ],
  },
  {
    slug: "presences",
    table: "presences",
    title: "Présences",
    singular: "Présence",
    description: "Pointage quotidien des agents.",
    group: "Administration / RH",
    labelField: "date_presence",
    fields: [
      { name: "employe_id", label: "Employé", type: "ref", refModule: "employes", list: true },
      { name: "date_presence", label: "Date", type: "date", list: true, required: true },
      { name: "heure_arrivee", label: "Arrivée", type: "text", list: true },
      { name: "heure_depart", label: "Départ", type: "text", list: true },
      STATUT(["Présent", "Absent", "Retard", "Mission"]),
      { name: "observation", label: "Observation", type: "textarea" },
    ],
  },
  {
    slug: "salaires",
    table: "salaires",
    title: "Salaires",
    singular: "Bulletin de salaire",
    description: "Paie mensuelle : brut, primes, retenues et net à payer.",
    group: "Administration / RH",
    labelField: "periode",
    fields: [
      { name: "employe_id", label: "Employé", type: "ref", refModule: "employes", list: true },
      { name: "periode", label: "Période", type: "text", list: true, required: true },
      { name: "brut", label: "Brut", type: "number", list: true },
      { name: "primes", label: "Primes", type: "number", list: true },
      { name: "retenues", label: "Retenues", type: "number", list: true },
      { name: "net", label: "Net à payer", type: "number", list: true },
      STATUT(["Préparé", "Validé", "Payé"]),
    ],
  },
  {
    slug: "clients",
    table: "clients",
    title: "Clients",
    singular: "Client",
    description: "Répertoire des clients et bénéficiaires facturés.",
    group: "Données commerciales",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom / Raison sociale", type: "text", list: true, required: true },
      { name: "contact", label: "Personne de contact", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "email", label: "E-mail", type: "text" },
      { name: "adresse", label: "Adresse", type: "text", list: true },
      { name: "categorie", label: "Catégorie", type: "text" },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "fournisseurs",
    table: "fournisseurs",
    title: "Fournisseurs",
    singular: "Fournisseur",
    description: "Répertoire des fournisseurs et prestataires.",
    group: "Données commerciales",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom / Raison sociale", type: "text", list: true, required: true },
      { name: "contact", label: "Personne de contact", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "email", label: "E-mail", type: "text" },
      { name: "adresse", label: "Adresse", type: "text" },
      { name: "domaine", label: "Domaine", type: "text", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "achats",
    table: "achats",
    title: "Achats",
    singular: "Achat",
    description: "Commandes et acquisitions auprès des fournisseurs.",
    group: "Données commerciales",
    labelField: "reference",
    fields: [
      { name: "reference", label: "Référence", type: "text", list: true, required: true },
      {
        name: "fournisseur_id",
        label: "Fournisseur",
        type: "ref",
        refModule: "fournisseurs",
        list: true,
      },
      { name: "designation", label: "Désignation", type: "text", list: true },
      { name: "date_achat", label: "Date", type: "date", list: true, required: true },
      { name: "quantite", label: "Quantité", type: "number", list: true },
      { name: "montant", label: "Montant", type: "number", list: true },
      STATUT(["Commandé", "Reçu", "Payé", "Annulé"]),
    ],
  },
  {
    slug: "ventes",
    table: "ventes",
    title: "Ventes",
    singular: "Vente",
    description: "Ventes et facturations aux clients.",
    group: "Données commerciales",
    labelField: "reference",
    fields: [
      { name: "reference", label: "Référence", type: "text", list: true, required: true },
      { name: "client_id", label: "Client", type: "ref", refModule: "clients", list: true },
      { name: "designation", label: "Désignation", type: "text", list: true },
      { name: "date_vente", label: "Date", type: "date", list: true, required: true },
      { name: "quantite", label: "Quantité", type: "number", list: true },
      { name: "montant", label: "Montant", type: "number", list: true },
      STATUT(["Facturé", "Payé", "Annulé"]),
    ],
  },
  {
    slug: "budgets",
    table: "budgets",
    title: "Budgets",
    singular: "Ligne budgétaire",
    description: "Prévisions et réalisations budgétaires par exercice.",
    group: "Données commerciales",
    labelField: "intitule",
    fields: [
      { name: "intitule", label: "Intitulé", type: "text", list: true, required: true },
      { name: "exercice", label: "Exercice", type: "text", list: true, required: true },
      { name: "categorie", label: "Catégorie", type: "text", list: true },
      { name: "service", label: "Service", type: "text" },
      { name: "montant_prevu", label: "Montant prévu", type: "number", list: true },
      { name: "montant_realise", label: "Montant réalisé", type: "number", list: true },
      STATUT(["Ouvert", "Clôturé"]),
    ],
  },
  {
    slug: "articles",
    table: "articles",
    title: "Articles",
    singular: "Article",
    description: "Catalogue des articles en magasin avec seuils d'alerte.",
    group: "Stock",
    labelField: "designation",
    fields: [
      { name: "code", label: "Code", type: "text", list: true },
      { name: "designation", label: "Désignation", type: "text", list: true, required: true },
      { name: "categorie", label: "Catégorie", type: "text", list: true },
      { name: "unite", label: "Unité", type: "text" },
      { name: "prix_unitaire", label: "Prix unitaire", type: "number", list: true },
      { name: "quantite_stock", label: "Quantité en stock", type: "number", list: true },
      { name: "seuil_alerte", label: "Seuil d'alerte", type: "number", list: true },
      { name: "magasin", label: "Magasin / Dépôt", type: "text", list: true },
    ],
  },
  {
    slug: "mouvements_stock",
    table: "mouvements_stock",
    title: "Mouvements de stock",
    singular: "Mouvement",
    description: "Entrées et sorties de magasin.",
    group: "Stock",
    labelField: "reference",
    fields: [
      { name: "article_id", label: "Article", type: "ref", refModule: "articles", list: true },
      {
        name: "type_mouvement",
        label: "Type",
        type: "select",
        list: true,
        required: true,
        options: ["Entrée", "Sortie", "Ajustement"],
      },
      { name: "quantite", label: "Quantité", type: "number", list: true },
      { name: "date_mouvement", label: "Date", type: "date", list: true, required: true },
      { name: "service", label: "Service", type: "text", list: true },
      { name: "motif", label: "Motif", type: "textarea" },
      { name: "reference", label: "Référence", type: "text" },
    ],
  },
  {
    slug: "vehicules",
    table: "vehicules",
    title: "Véhicules",
    singular: "Véhicule",
    description: "Parc automobile : affectation, chauffeur et kilométrage.",
    group: "Charroi",
    labelField: "immatriculation",
    labelField2: "marque",
    fields: [
      { name: "immatriculation", label: "Immatriculation", type: "text", list: true, required: true },
      { name: "marque", label: "Marque", type: "text", list: true },
      { name: "modele", label: "Modèle", type: "text", list: true },
      { name: "type_vehicule", label: "Type", type: "text", list: true },
      { name: "affectation", label: "Affectation", type: "text", list: true },
      { name: "chauffeur", label: "Chauffeur", type: "text", list: true },
      { name: "kilometrage", label: "Kilométrage", type: "number", list: true, suffix: "km" },
      STATUT(["En service", "En entretien", "Immobilisé", "Réformé"]),
    ],
  },
  {
    slug: "carburant",
    table: "carburant",
    title: "Carburant",
    singular: "Bon de carburant",
    description: "Servis de carburant par véhicule et par station.",
    group: "Charroi",
    labelField: "bon",
    fields: [
      { name: "vehicule_id", label: "Véhicule", type: "ref", refModule: "vehicules", list: true },
      { name: "date_service", label: "Date", type: "date", list: true, required: true },
      { name: "litres", label: "Litres", type: "number", list: true, suffix: "L" },
      { name: "prix_total", label: "Montant", type: "number", list: true },
      { name: "kilometrage", label: "Kilométrage", type: "number", list: true, suffix: "km" },
      { name: "station", label: "Station / Dépôt", type: "text", list: true },
      { name: "bon", label: "N° de bon", type: "text", list: true },
    ],
  },
  {
    slug: "entretiens",
    table: "entretiens",
    title: "Entretiens",
    singular: "Entretien",
    description: "Maintenance et réparations du charroi.",
    group: "Charroi",
    labelField: "nature",
    fields: [
      { name: "vehicule_id", label: "Véhicule", type: "ref", refModule: "vehicules", list: true },
      { name: "date_entretien", label: "Date", type: "date", list: true, required: true },
      { name: "nature", label: "Nature", type: "text", list: true },
      { name: "garage", label: "Garage", type: "text", list: true },
      { name: "cout", label: "Coût", type: "number", list: true },
      STATUT(["Planifié", "En cours", "Terminé"]),
    ],
  },
  {
    slug: "associations",
    table: "associations",
    title: "Organisations communautaires",
    singular: "Organisation",
    description: "CNAC, associations, coopératives, fédérations et unions.",
    group: "Communauté",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      {
        name: "type_organisation",
        label: "Type",
        type: "select",
        list: true,
        required: true,
        options: ["CNAC", "Association", "Coopérative", "Fédération", "Union"],
      },
      { name: "localite", label: "Localité", type: "text", list: true },
      { name: "province", label: "Province", type: "text", list: true },
      { name: "responsable", label: "Responsable", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text" },
      { name: "date_creation", label: "Date de création", type: "date" },
      STATUT(["Active", "Inactive"]),
    ],
  },
  {
    slug: "membres",
    table: "membres",
    title: "Membres",
    singular: "Membre",
    description: "Membres affiliés aux organisations communautaires.",
    group: "Communauté",
    labelField: "nom",
    labelField2: "prenom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "prenom", label: "Prénom", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "sexe", label: "Sexe", type: "select", list: true, options: ["M", "F"] },
      { name: "localite", label: "Localité", type: "text", list: true },
      {
        name: "association_id",
        label: "Organisation",
        type: "ref",
        refModule: "associations",
        list: true,
      },
      { name: "cotisation", label: "Cotisation", type: "number", list: true },
      { name: "date_adhesion", label: "Adhésion", type: "date" },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "operations",
    table: "operations",
    title: "Caisse & opérations",
    singular: "Opération",
    description: "Entrées et sorties de caisse.",
    group: "Finances & suivi",
    labelField: "libelle",
    fields: [
      { name: "libelle", label: "Libellé", type: "text", list: true, required: true },
      {
        name: "type_operation",
        label: "Type",
        type: "select",
        list: true,
        required: true,
        options: ["Entrée", "Sortie"],
      },
      { name: "compte", label: "Compte", type: "text", list: true },
      { name: "montant", label: "Montant", type: "number", list: true },
      { name: "date_operation", label: "Date", type: "date", list: true, required: true },
      { name: "beneficiaire", label: "Bénéficiaire", type: "text", list: true },
      STATUT(["En attente", "Validée", "Annulée"]),
    ],
  },
  {
    slug: "transactions_mobile",
    table: "transactions_mobile",
    title: "Mobile money",
    singular: "Transaction",
    description: "Opérations électroniques et mobile money.",
    group: "Finances & suivi",
    labelField: "reference",
    fields: [
      {
        name: "operateur",
        label: "Opérateur",
        type: "select",
        list: true,
        required: true,
        options: ["Lumicash", "Ecocash", "M-Pesa", "Airtel Money", "Autre"],
      },
      {
        name: "type_operation",
        label: "Type",
        type: "select",
        list: true,
        required: true,
        options: ["Dépôt", "Retrait", "Transfert", "Paiement"],
      },
      { name: "reference", label: "Référence", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "montant", label: "Montant", type: "number", list: true },
      { name: "commission", label: "Commission", type: "number", list: true },
      { name: "date_operation", label: "Date", type: "date", list: true, required: true },
      { name: "agent", label: "Agent", type: "text" },
      STATUT(["Réussie", "En attente", "Échouée"]),
    ],
  },
  {
    slug: "programmes",
    table: "programmes",
    title: "Programmes",
    singular: "Programme",
    description: "Programmes institutionnels et leurs enveloppes.",
    group: "Projets & partenariats",
    labelField: "intitule",
    fields: [
      { name: "intitule", label: "Intitulé", type: "text", list: true, required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "responsable", label: "Responsable", type: "text", list: true },
      { name: "date_debut", label: "Début", type: "date", list: true },
      { name: "date_fin", label: "Fin", type: "date", list: true },
      { name: "budget", label: "Budget", type: "number", list: true },
      STATUT(["En préparation", "En cours", "Clôturé"]),
    ],
  },
  {
    slug: "partenaires",
    table: "partenaires",
    title: "Partenaires",
    singular: "Partenaire",
    description: "Partenaires techniques et financiers.",
    group: "Projets & partenariats",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "type_partenaire", label: "Type", type: "text", list: true },
      { name: "pays", label: "Pays", type: "text", list: true },
      { name: "contact", label: "Contact", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text" },
      { name: "domaine", label: "Domaine", type: "text", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "projets",
    table: "projets",
    title: "Projets",
    singular: "Projet",
    description: "Projets rattachés aux programmes et partenaires.",
    group: "Projets & partenariats",
    labelField: "titre",
    fields: [
      { name: "titre", label: "Titre", type: "text", list: true, required: true },
      {
        name: "programme_id",
        label: "Programme",
        type: "ref",
        refModule: "programmes",
        list: true,
      },
      {
        name: "partenaire_id",
        label: "Partenaire",
        type: "ref",
        refModule: "partenaires",
        list: true,
      },
      { name: "responsable", label: "Responsable", type: "text", list: true },
      { name: "zone", label: "Zone d'intervention", type: "text", list: true },
      { name: "budget", label: "Budget", type: "number", list: true },
      { name: "date_debut", label: "Début", type: "date" },
      { name: "date_fin", label: "Fin", type: "date" },
      { name: "avancement", label: "Avancement (%)", type: "number", list: true, suffix: "%" },
      STATUT(["En préparation", "En cours", "Suspendu", "Clôturé"]),
    ],
  },
  {
    slug: "archives",
    table: "archives",
    title: "Archives",
    singular: "Document archivé",
    description: "Documents classés et leur emplacement physique.",
    group: "Finances & suivi",
    labelField: "titre",
    fields: [
      { name: "titre", label: "Titre", type: "text", list: true, required: true },
      { name: "categorie", label: "Catégorie", type: "text", list: true },
      { name: "reference", label: "Référence", type: "text", list: true },
      { name: "service", label: "Service", type: "text", list: true },
      { name: "date_document", label: "Date du document", type: "date", list: true },
      { name: "emplacement", label: "Emplacement", type: "text", list: true },
      { name: "observation", label: "Observation", type: "textarea" },
    ],
  },
];

export const MODULE_MAP: Record<string, ModuleDef> = Object.fromEntries(
  MODULES.map((m) => [m.slug, m]),
);

export const GROUPS = [
  "Administration / RH",
  "Communauté",
  "Données commerciales",
  "Stock",
  "Charroi",
  "Finances & suivi",
  "Projets & partenariats",
];

export function modulesOfGroup(group: string): ModuleDef[] {
  return MODULES.filter((m) => m.group === group);
}
