/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as StructureProfilsRouteImport } from './routes/structure-profils'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as MModuleRouteImport } from './routes/m.$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureProfilsRoute = StructureProfilsRouteImport.update({
  id: '/structure-profils',
  path: '/structure-profils',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleRoute = MModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/statistiques': typeof StatistiquesRoute
  '/structure-profils': typeof StructureProfilsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/m/$module': typeof MModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/statistiques': typeof StatistiquesRoute
  '/structure-profils': typeof StructureProfilsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/m/$module': typeof MModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/statistiques': typeof StatistiquesRoute
  '/structure-profils': typeof StructureProfilsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/m/$module': typeof MModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guide'
    | '/parametres'
    | '/rapports'
    | '/statistiques'
    | '/structure-profils'
    | '/tableau-de-bord'
    | '/m/$module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guide'
    | '/parametres'
    | '/rapports'
    | '/statistiques'
    | '/structure-profils'
    | '/tableau-de-bord'
    | '/m/$module'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/guide'
    | '/parametres'
    | '/rapports'
    | '/statistiques'
    | '/structure-profils'
    | '/tableau-de-bord'
    | '/m/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GuideRoute: typeof GuideRoute
  ParametresRoute: typeof ParametresRoute
  RapportsRoute: typeof RapportsRoute
  StatistiquesRoute: typeof StatistiquesRoute
  StructureProfilsRoute: typeof StructureProfilsRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  MModuleRoute: typeof MModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure-profils': {
      id: '/structure-profils'
      path: '/structure-profils'
      fullPath: '/structure-profils'
      preLoaderRoute: typeof StructureProfilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module': {
      id: '/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof MModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GuideRoute: GuideRoute,
  ParametresRoute: ParametresRoute,
  RapportsRoute: RapportsRoute,
  StatistiquesRoute: StatistiquesRoute,
  StructureProfilsRoute: StructureProfilsRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  MModuleRoute: MModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
